#!/bin/bash


CALLS="10000000"
FLAGS="1111111"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 8 --add_higgs 550,32.87,1.4286,0,-0.7,0 --add_higgs 510,48.38,0,1.4286,0,0.7  -v 1 -K -D -Q
