#!/bin/bash


CALLS="10000000"
FLAGS="0000000"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX_S -I $FLAGS -N $CALLS -E 13 --add_higgs 550,37.89,1.4286,0,0,0 --add_higgs 510,55.11,0,1.4286,0,0  -v 1 -D -F -r 0.5 -Q
