#!/bin/bash

CALLS="100000000"
FLAGS="0000010"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX_S -I $FLAGS -N $CALLS -E 13 -D --add_higgs 500,30.00,0.8631,0.9881,0,0 --add_higgs 800,146.61,-1.1572,0.9881,0,0  -v 1 -r 1.0 -Q 
