#!/bin/bash

CALLS="10000000"
FLAGS="0000011"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX_S -I $FLAGS -N $CALLS -E 8 -D --add_higgs 500,30,0.863,0.988,-0.642,0.484 --add_higgs 800,90,-1.157,0.988,0.348,0.484 -v 1
