#!/bin/bash

CALLS="10000000"
FLAGS="0000011"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX_S -I $FLAGS -N $CALLS -E 8 -D --add_higgs 500,30,1.373,0.236,-0.725,0.116 --add_higgs 800,90,-0.447,1.377,-0.0865,0.675 -v 1
