#!/bin/bash


CALLS="10000000"
FLAGS="1111111"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 13 --add_higgs 550,38.66,1.4286,0,-0.7,0 --add_higgs 510,56.24,0,1.4286,0,0.7 -L -F -v 1 -D -r 0.5 -K -Q
