#!/bin/bash


CALLS="10000000"
FLAGS="0000011"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX_S -I $FLAGS -N $CALLS -E 8 -D --add_higgs 550,32.77,1.4286,0,-0.0,0 --add_higgs 510,48.22,0,1.4286,0,0.0 -v 1
