#!/bin/bash

CALLS="1000000"
FLAGS="1111111"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 8 -D --add_higgs 550,34.36,1.4286,0,-0.7,0 --add_higgs 700,70.48,0,1.4286,0,0.7 -m 0
