#!/bin/bash


CALLS="1000000"
FLAGS="1111111"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 13 --add_higgs 550,34.56,1.4286,0,0.0,0 --add_higgs 510,49.28,0,1.4286,0,0.0  -v 1 -D  -r 1.0 --QCD=qcd/binned_lhc13
