#!/bin/bash


CALLS="10000000"
FLAGS="1111111"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 8 --add_higgs 550,37.89,1.4286,0,0.0,0 --add_higgs 510,55.11,0,1.4286,0,0.0 -L -F -v 1 -D  -r 1.0  -Q
