#!/bin/bash


CALLS="1000000"
FLAGS="0000011"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi

### Gamma2 = 37.89
./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 13 --add_higgs 550,34.89,1.4286,0,-0.7,0 --add_higgs 510,55.11,0,1.4286,0,0.7  -v 1 -D  -r 1.0 
