#!/bin/bash

CALLS="10000000"
FLAGS="1111111"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX -I $FLAGS -N $CALLS -E 13 -D --add_higgs 550,37.74,1.4286,0,-0.7,0 --add_higgs 700,92.26,0,1.4286,0,0.7 -L -F -v 1  -r 1.0 -K -Q
