#!/bin/bash

CALLS="100000000"
FLAGS="0000000"

if [ $# -eq 2 ]
then
FLAGS=$1
CALLS=$2
fi

if [ $# -eq 1 ]
then
FLAGS=$1
fi


./bin/Integrate_pp_ttX_S -I $FLAGS -N $CALLS -E 13 -D --add_higgs 550,47.74,1.4286,0,0,0 --add_higgs 700,92.26,0,1.4286,0,0 -v 1  -r 1.0 -Q -F
