#!/bin/bash


FILES=2RE_PHIxQCD_UID_*	
for f in $FILES
do
  echo "Processing $f file..."
  sed -e 's/AMP_/UID_/g' <$f >$f.e
  mv $f.e $f
done

FILES=PHIxPHI_UID_*	
for f in $FILES
do
  echo "Processing $f file..."
  sed -e 's/AMP_/UID_/g' <$f >$f.e
  mv $f.e $f
done
